CREATE DATABASE DB_2IPI;
USE DB_2IPI;

 CREATE TABLE IF NOT EXISTS TB_CEP(

    NOME    VARCHAR(100),
    NASC    DATE,
    CPF     INT(15),
    RG      INT(15),
    TEL     INT(15),
    ID_CEP  INT PRIMARY KEY AUTO_INCREMENT ,
    CEP     VARCHAR(10)     NOT NULL,
    RUA     VARCHAR (100)   NOT NULL,
    NUMERO  VARCHAR(4)      NOT NULL,
    COMP    VARCHAR(60),
    BAIRRO  VARCHAR(100)    NOT NULL,
    CIDADE  VARCHAR(100)    NOT NULL,
    UF      CHAR(2)         NOT NULL,
    ASS     VARCHAR(20),
    MSG     VARCHAR(100),
    SENHA   VARCHAR
 );
